version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: npx chromatic --project-token=eqp57mm70cj --exit-zero-on-changes
            - run: |
                if [ $CIRCLE_BRANCH = "master" ]
                then
                  yarn release
                fi
workflows:
    build-and-test:
      jobs:
        - build-and-test